//------------------------------------------------------------------------------
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated.
//
//------------------------------------------------------------------------------
// Copyright (c) rubicon IT GmbH, www.rubicon.eu
//
// See the NOTICE file distributed with this work for additional information
// regarding copyright ownership.  rubicon licenses this file to you under 
// the Apache License, Version 2.0 (the "License"); you may not use this 
// file except in compliance with the License.  You may obtain a copy of the 
// License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software 
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT 
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the 
// License for the specific language governing permissions and limitations
// under the License.
// 
using System;
using ActiveAttributes.Core.Contexts;
using Remotion;

namespace ActiveAttributes.Core.Invocations
{
  public class FuncInvocation<TInstance, TR> : Invocation
  {
    private readonly FuncInvocationContext<TInstance, TR> _context;
    private readonly Func<TR> _func;

    public FuncInvocation (FuncInvocationContext<TInstance, TR> context, Func<TR> func)
    {
      _context = context;
      _func = func;
    }

    public override IInvocationContext Context
    {
      get { return _context; }
    }

    public override void Proceed ()
    {
      _context.ReturnValue = _func ();
    }
  }
  public class FuncInvocation<TInstance, TA1, TA2, TR> : Invocation
  {
    private readonly FuncInvocationContext<TInstance, TA1, TA2, TR> _context;
    private readonly Func<TA1, TA2, TR> _func;

    public FuncInvocation (FuncInvocationContext<TInstance, TA1, TA2, TR> context, Func<TA1, TA2, TR> func)
    {
      _context = context;
      _func = func;
    }

    public override IInvocationContext Context
    {
      get { return _context; }
    }

    public override void Proceed ()
    {
      _context.ReturnValue = _func (_context.Arg1, _context.Arg2);
    }
  }
  public class FuncInvocation<TInstance, TA1, TA2, TA3, TR> : Invocation
  {
    private readonly FuncInvocationContext<TInstance, TA1, TA2, TA3, TR> _context;
    private readonly Func<TA1, TA2, TA3, TR> _func;

    public FuncInvocation (FuncInvocationContext<TInstance, TA1, TA2, TA3, TR> context, Func<TA1, TA2, TA3, TR> func)
    {
      _context = context;
      _func = func;
    }

    public override IInvocationContext Context
    {
      get { return _context; }
    }

    public override void Proceed ()
    {
      _context.ReturnValue = _func (_context.Arg1, _context.Arg2, _context.Arg3);
    }
  }
  public class FuncInvocation<TInstance, TA1, TA2, TA3, TA4, TR> : Invocation
  {
    private readonly FuncInvocationContext<TInstance, TA1, TA2, TA3, TA4, TR> _context;
    private readonly Func<TA1, TA2, TA3, TA4, TR> _func;

    public FuncInvocation (FuncInvocationContext<TInstance, TA1, TA2, TA3, TA4, TR> context, Func<TA1, TA2, TA3, TA4, TR> func)
    {
      _context = context;
      _func = func;
    }

    public override IInvocationContext Context
    {
      get { return _context; }
    }

    public override void Proceed ()
    {
      _context.ReturnValue = _func (_context.Arg1, _context.Arg2, _context.Arg3, _context.Arg4);
    }
  }
  public class FuncInvocation<TInstance, TA1, TA2, TA3, TA4, TA5, TR> : Invocation
  {
    private readonly FuncInvocationContext<TInstance, TA1, TA2, TA3, TA4, TA5, TR> _context;
    private readonly Func<TA1, TA2, TA3, TA4, TA5, TR> _func;

    public FuncInvocation (FuncInvocationContext<TInstance, TA1, TA2, TA3, TA4, TA5, TR> context, Func<TA1, TA2, TA3, TA4, TA5, TR> func)
    {
      _context = context;
      _func = func;
    }

    public override IInvocationContext Context
    {
      get { return _context; }
    }

    public override void Proceed ()
    {
      _context.ReturnValue = _func (_context.Arg1, _context.Arg2, _context.Arg3, _context.Arg4, _context.Arg5);
    }
  }
  public class FuncInvocation<TInstance, TA1, TA2, TA3, TA4, TA5, TA6, TR> : Invocation
  {
    private readonly FuncInvocationContext<TInstance, TA1, TA2, TA3, TA4, TA5, TA6, TR> _context;
    private readonly Func<TA1, TA2, TA3, TA4, TA5, TA6, TR> _func;

    public FuncInvocation (FuncInvocationContext<TInstance, TA1, TA2, TA3, TA4, TA5, TA6, TR> context, Func<TA1, TA2, TA3, TA4, TA5, TA6, TR> func)
    {
      _context = context;
      _func = func;
    }

    public override IInvocationContext Context
    {
      get { return _context; }
    }

    public override void Proceed ()
    {
      _context.ReturnValue = _func (_context.Arg1, _context.Arg2, _context.Arg3, _context.Arg4, _context.Arg5, _context.Arg6);
    }
  }
  public class FuncInvocation<TInstance, TA1, TA2, TA3, TA4, TA5, TA6, TA7, TR> : Invocation
  {
    private readonly FuncInvocationContext<TInstance, TA1, TA2, TA3, TA4, TA5, TA6, TA7, TR> _context;
    private readonly Func<TA1, TA2, TA3, TA4, TA5, TA6, TA7, TR> _func;

    public FuncInvocation (FuncInvocationContext<TInstance, TA1, TA2, TA3, TA4, TA5, TA6, TA7, TR> context, Func<TA1, TA2, TA3, TA4, TA5, TA6, TA7, TR> func)
    {
      _context = context;
      _func = func;
    }

    public override IInvocationContext Context
    {
      get { return _context; }
    }

    public override void Proceed ()
    {
      _context.ReturnValue = _func (_context.Arg1, _context.Arg2, _context.Arg3, _context.Arg4, _context.Arg5, _context.Arg6, _context.Arg7);
    }
  }
  public class FuncInvocation<TInstance, TA1, TA2, TA3, TA4, TA5, TA6, TA7, TA8, TR> : Invocation
  {
    private readonly FuncInvocationContext<TInstance, TA1, TA2, TA3, TA4, TA5, TA6, TA7, TA8, TR> _context;
    private readonly Func<TA1, TA2, TA3, TA4, TA5, TA6, TA7, TA8, TR> _func;

    public FuncInvocation (FuncInvocationContext<TInstance, TA1, TA2, TA3, TA4, TA5, TA6, TA7, TA8, TR> context, Func<TA1, TA2, TA3, TA4, TA5, TA6, TA7, TA8, TR> func)
    {
      _context = context;
      _func = func;
    }

    public override IInvocationContext Context
    {
      get { return _context; }
    }

    public override void Proceed ()
    {
      _context.ReturnValue = _func (_context.Arg1, _context.Arg2, _context.Arg3, _context.Arg4, _context.Arg5, _context.Arg6, _context.Arg7, _context.Arg8);
    }
  }
}
